# Site
repository: https://hyukyeon.github.io/
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Hyukyeon Lee
title: Wireless Communications PHY & Modem SoC Researcher
email: hyukyeon@yonsei.ac.kr
phone: +82-10-5312-2177
website: https://hyukyeon.github.io/

# Social links
github_username: hyukyeon
# dribbble_username: jekyll
facebook_username: hyukyeon
# flickr_username: jekyll
linkedin_username: hyukyeon

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 I am currently pursuing the **M.S. & Ph.D degree** with the Department of **Electrical and Electronic Engineering** in **Yonsei University**, Seoul, Korea (Advisior : Prof. Jaeseok Kim). My research intersets include **wireless communications PHY** and **next-generation modem SoC architecture**.

  **RESEARCH INTEREST**
    - Wireless Communications PHY (5G/802.11ad/802.11ax)
    - High-Dimensional MIMO Signal Processing
    - Compressed Sensing for mmWave Sparse Channel Estimation
    - Hybrid Precoding & Low-Resolution ADC for mmWave Systems
    - 5G/Wifi Modem SoC Architecture

# Projects Section
projects_title: Research Projects 

# Experience Section
experience_title: Experience & Awards 

# Education Section
education_title: Publications

# More Section
more_title: Skills & Interests
more_content: |  
               **Experienced Skills** 
               - Wireless Communication PHY Signal Processing (MATLAB/Python)
               - Linux Programming (Shell Script)
               - Verilog HDL
               - ASIC Front-end Design Flow (Design Compiler, PrimeTime, ModelSim, VCS)
               - ASIC Back-end Design Flow (IC Compiler) 
               - FPGA Design (Xilinx ISE, Vivado)
  
               **Current Research Interests**
               - User Schedulling in mmWave low-resolution ADCs systems
               - Sparse channel estimation in frequency-selective mmWave hybird systems 
               - Lattice reduction-aided massive MIMO detection 

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
